#cloud-config

timezone: Asia/Tokyo
locale: ja_JP.utf8

user: user
password: user
chpasswd: {expire: False}

bootcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

apt:
  preserve_sources_list: true
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable

packages:
  - docker-ce
  - make
package_update: true
package_upgrade: true

runcmd:
  - usermod -aG docker user
  - sudo systemctl start docker

write_files:
  - content: |
      run :
      	docker build -t hoge .
      	docker run hoge bash -c "go run hoge.go"
    path: /home/user/Makefile
  - content: |
      package main

      import ("fmt"
              "time"
      )

      func main() {
        for{
        time.Sleep(time.Second * 1)
        fmt.Printf("Hello World\n")
        }
      }
    path: /home/user/hoge.go
  - content: |
      FROM golang
      WORKDIR /root
      COPY hoge.go /root
    path: /home/user/Dockerfile

# prob : https://blog.icttoracon.net/2021/09/03/%e6%ad%a2%e3%81%be%e3%82%89%e3%81%aa%e3%81%84/